/* Generated By:JavaCC: Do not edit this line. PFConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PFConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BA = 5;
  /** RegularExpression Id. */
  int BC = 6;
  /** RegularExpression Id. */
  int PA = 7;
  /** RegularExpression Id. */
  int PC = 8;
  /** RegularExpression Id. */
  int CA = 9;
  /** RegularExpression Id. */
  int CC = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int COMA = 12;
  /** RegularExpression Id. */
  int PUNTO = 13;
  /** RegularExpression Id. */
  int DP = 14;
  /** RegularExpression Id. */
  int PCOMA = 15;
  /** RegularExpression Id. */
  int GB = 16;
  /** RegularExpression Id. */
  int CREATE = 17;
  /** RegularExpression Id. */
  int PAGE = 18;
  /** RegularExpression Id. */
  int WITH = 19;
  /** RegularExpression Id. */
  int TABLE = 20;
  /** RegularExpression Id. */
  int CLASS = 21;
  /** RegularExpression Id. */
  int HEADERS = 22;
  /** RegularExpression Id. */
  int HEADER = 23;
  /** RegularExpression Id. */
  int FOOTER = 24;
  /** RegularExpression Id. */
  int SIDEBAR = 25;
  /** RegularExpression Id. */
  int NAV = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int ITEMS = 28;
  /** RegularExpression Id. */
  int AUDIO = 29;
  /** RegularExpression Id. */
  int VIDEO = 30;
  /** RegularExpression Id. */
  int LIST = 31;
  /** RegularExpression Id. */
  int LINK = 32;
  /** RegularExpression Id. */
  int PARAGRAPH = 33;
  /** RegularExpression Id. */
  int TITLE = 34;
  /** RegularExpression Id. */
  int SUBTITLE = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int COLUMNS = 37;
  /** RegularExpression Id. */
  int ROWS = 38;
  /** RegularExpression Id. */
  int STYLE = 39;
  /** RegularExpression Id. */
  int SMALLBLOCK = 40;
  /** RegularExpression Id. */
  int MEDIUMBLOCK = 41;
  /** RegularExpression Id. */
  int LARGEBLOCK = 42;
  /** RegularExpression Id. */
  int YES = 43;
  /** RegularExpression Id. */
  int NO = 44;
  /** RegularExpression Id. */
  int SECTION = 45;
  /** RegularExpression Id. */
  int IMAGE = 46;
  /** RegularExpression Id. */
  int SOURCE = 47;
  /** RegularExpression Id. */
  int WIDTH = 48;
  /** RegularExpression Id. */
  int PX = 49;
  /** RegularExpression Id. */
  int TIMES = 50;
  /** RegularExpression Id. */
  int HEIGHT = 51;
  /** RegularExpression Id. */
  int MOV = 52;
  /** RegularExpression Id. */
  int MP4 = 53;
  /** RegularExpression Id. */
  int MP3 = 54;
  /** RegularExpression Id. */
  int WAV = 55;
  /** RegularExpression Id. */
  int JPG = 56;
  /** RegularExpression Id. */
  int PNG = 57;
  /** RegularExpression Id. */
  int IDG = 58;
  /** RegularExpression Id. */
  int ID = 59;
  /** RegularExpression Id. */
  int ENTERO = 60;
  /** RegularExpression Id. */
  int REAL = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"_\"",
    "\"create\"",
    "\"page\"",
    "\"with\"",
    "\"table\"",
    "\"class\"",
    "\"headers\"",
    "\"header\"",
    "\"footer\"",
    "\"sidebar\"",
    "\"nav\"",
    "\"div\"",
    "\"items\"",
    "\"audio\"",
    "\"video\"",
    "\"list\"",
    "\"link\"",
    "\"paragraph\"",
    "\"title\"",
    "\"subtitle\"",
    "\"and\"",
    "\"columns\"",
    "\"rows\"",
    "\"style\"",
    "\"smallBlock\"",
    "\"mediumBlock\"",
    "\"largeBlock\"",
    "\"yes\"",
    "\"no\"",
    "\"section\"",
    "\"image\"",
    "\"source\"",
    "\"width\"",
    "\"px\"",
    "\"times\"",
    "\"height\"",
    "\"mov\"",
    "\"mp4\"",
    "\"mp3\"",
    "\"wav\"",
    "\"jpg\"",
    "\"png\"",
    "\"id\"",
    "<ID>",
    "<ENTERO>",
    "<REAL>",
  };

}
